# Generated by Django 4.2.3 on 2023-07-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.TextField(default=models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
        ),
    ]
